language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (rustup component add rustfmt-preview clippy-preview) fi
script:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo fmt --all -- --check) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo clippy -- -D warnings) fi
  - cargo test --all
  - cargo build --manifest-path=./graphql_client/examples/github/Cargo.toml
  - cargo build --manifest-path=./graphql_client_cli/Cargo.toml
